name: Kynema-FMB Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Formatting:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '22'
        check-path: '.'
